// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_io_array_io,hls_ip_2022_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.029313,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1306,HLS_SYN_LUT=2223,HLS_VERSION=2022_1}" *)

module array_io (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_o_0_address0,
        d_o_0_ce0,
        d_o_0_we0,
        d_o_0_d0,
        d_o_1_address0,
        d_o_1_ce0,
        d_o_1_we0,
        d_o_1_d0,
        d_i_0_address0,
        d_i_0_ce0,
        d_i_0_q0,
        d_i_1_address0,
        d_i_1_ce0,
        d_i_1_q0
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] d_o_0_address0;
output   d_o_0_ce0;
output   d_o_0_we0;
output  [15:0] d_o_0_d0;
output  [3:0] d_o_1_address0;
output   d_o_1_ce0;
output   d_o_1_we0;
output  [15:0] d_o_1_d0;
output  [3:0] d_i_0_address0;
output   d_i_0_ce0;
input  [15:0] d_i_0_q0;
output  [3:0] d_i_1_address0;
output   d_i_1_ce0;
input  [15:0] d_i_1_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] d_o_0_address0;
reg d_o_0_ce0;
reg d_o_0_we0;
reg[15:0] d_o_0_d0;
reg[3:0] d_o_1_address0;
reg d_o_1_ce0;
reg d_o_1_we0;
reg[15:0] d_o_1_d0;
reg[3:0] d_i_0_address0;
reg d_i_0_ce0;
reg[3:0] d_i_1_address0;
reg d_i_1_ce0;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] acc_0;
reg   [31:0] acc_1;
reg   [31:0] acc_2;
reg   [31:0] acc_3;
reg   [31:0] acc_4;
reg   [31:0] acc_5;
reg   [31:0] acc_6;
reg   [31:0] acc_7;
reg  signed [15:0] d_i_0_load_reg_1310;
wire    ap_CS_fsm_state2;
reg  signed [15:0] d_i_1_load_reg_1316;
wire   [15:0] add_ln69_fu_684_p2;
reg   [15:0] add_ln69_reg_1335;
wire    ap_CS_fsm_state3;
wire   [15:0] add_ln69_1_fu_698_p2;
reg   [15:0] add_ln69_1_reg_1343;
reg  signed [15:0] d_i_0_load_1_reg_1348;
reg  signed [15:0] d_i_1_load_1_reg_1354;
wire   [15:0] add_ln69_2_fu_712_p2;
reg   [15:0] add_ln69_2_reg_1373;
wire    ap_CS_fsm_state4;
wire   [15:0] add_ln69_3_fu_726_p2;
reg   [15:0] add_ln69_3_reg_1381;
reg  signed [15:0] d_i_0_load_2_reg_1386;
reg  signed [15:0] d_i_1_load_2_reg_1392;
wire   [15:0] add_ln69_4_fu_740_p2;
reg   [15:0] add_ln69_4_reg_1411;
wire    ap_CS_fsm_state5;
wire   [15:0] add_ln69_5_fu_754_p2;
reg   [15:0] add_ln69_5_reg_1419;
reg  signed [15:0] d_i_0_load_3_reg_1424;
reg  signed [15:0] d_i_1_load_3_reg_1430;
wire   [15:0] add_ln69_6_fu_768_p2;
reg   [15:0] add_ln69_6_reg_1449;
wire    ap_CS_fsm_state6;
wire   [15:0] add_ln69_7_fu_782_p2;
reg   [15:0] add_ln69_7_reg_1457;
reg  signed [15:0] d_i_0_load_4_reg_1462;
reg  signed [15:0] d_i_1_load_4_reg_1468;
wire   [15:0] add_ln69_8_fu_788_p2;
reg   [15:0] add_ln69_8_reg_1484;
wire    ap_CS_fsm_state7;
wire   [15:0] add_ln69_9_fu_793_p2;
reg   [15:0] add_ln69_9_reg_1489;
reg  signed [15:0] d_i_0_load_5_reg_1494;
reg  signed [15:0] d_i_1_load_5_reg_1500;
wire   [15:0] add_ln69_10_fu_798_p2;
reg   [15:0] add_ln69_10_reg_1516;
wire    ap_CS_fsm_state8;
wire   [15:0] add_ln69_11_fu_803_p2;
reg   [15:0] add_ln69_11_reg_1521;
reg  signed [15:0] d_i_0_load_6_reg_1526;
reg  signed [15:0] d_i_1_load_6_reg_1532;
wire   [15:0] add_ln69_12_fu_808_p2;
reg   [15:0] add_ln69_12_reg_1548;
wire    ap_CS_fsm_state9;
wire   [15:0] add_ln69_13_fu_813_p2;
reg   [15:0] add_ln69_13_reg_1553;
reg  signed [15:0] d_i_0_load_7_reg_1558;
reg  signed [15:0] d_i_1_load_7_reg_1564;
wire   [15:0] add_ln69_14_fu_818_p2;
reg   [15:0] add_ln69_14_reg_1580;
wire    ap_CS_fsm_state10;
wire   [15:0] add_ln69_15_fu_823_p2;
reg   [15:0] add_ln69_15_reg_1585;
reg  signed [15:0] d_i_0_load_8_reg_1590;
reg  signed [15:0] d_i_1_load_8_reg_1596;
wire   [15:0] add_ln69_16_fu_828_p2;
reg   [15:0] add_ln69_16_reg_1612;
wire    ap_CS_fsm_state11;
wire   [15:0] add_ln69_17_fu_833_p2;
reg   [15:0] add_ln69_17_reg_1617;
reg  signed [15:0] d_i_0_load_9_reg_1622;
reg  signed [15:0] d_i_1_load_9_reg_1628;
wire   [15:0] add_ln69_18_fu_838_p2;
reg   [15:0] add_ln69_18_reg_1644;
wire    ap_CS_fsm_state12;
wire   [15:0] add_ln69_19_fu_843_p2;
reg   [15:0] add_ln69_19_reg_1649;
reg  signed [15:0] d_i_0_load_10_reg_1654;
reg  signed [15:0] d_i_1_load_10_reg_1660;
wire   [15:0] add_ln69_20_fu_848_p2;
reg   [15:0] add_ln69_20_reg_1676;
wire    ap_CS_fsm_state13;
wire   [15:0] add_ln69_21_fu_853_p2;
reg   [15:0] add_ln69_21_reg_1681;
reg  signed [15:0] d_i_0_load_11_reg_1686;
reg  signed [15:0] d_i_1_load_11_reg_1692;
wire   [15:0] add_ln69_22_fu_864_p2;
reg   [15:0] add_ln69_22_reg_1708;
wire    ap_CS_fsm_state14;
wire   [15:0] add_ln69_23_fu_869_p2;
reg   [15:0] add_ln69_23_reg_1713;
wire   [16:0] add_ln67_1_fu_878_p2;
reg   [16:0] add_ln67_1_reg_1718;
wire   [15:0] add_ln69_24_fu_884_p2;
reg   [15:0] add_ln69_24_reg_1723;
wire   [16:0] add_ln67_5_fu_893_p2;
reg   [16:0] add_ln67_5_reg_1728;
wire   [15:0] add_ln69_25_fu_899_p2;
reg   [15:0] add_ln69_25_reg_1733;
wire   [16:0] add_ln67_9_fu_986_p2;
reg   [16:0] add_ln67_9_reg_1748;
wire    ap_CS_fsm_state15;
wire   [15:0] add_ln69_26_fu_992_p2;
reg   [15:0] add_ln69_26_reg_1753;
wire   [16:0] add_ln67_13_fu_1001_p2;
reg   [16:0] add_ln67_13_reg_1758;
wire   [15:0] add_ln69_27_fu_1007_p2;
reg   [15:0] add_ln69_27_reg_1763;
wire   [16:0] add_ln67_17_fu_1094_p2;
reg   [16:0] add_ln67_17_reg_1778;
wire    ap_CS_fsm_state16;
wire   [15:0] add_ln69_28_fu_1100_p2;
reg   [15:0] add_ln69_28_reg_1783;
wire   [16:0] add_ln67_21_fu_1109_p2;
reg   [16:0] add_ln67_21_reg_1788;
wire   [15:0] add_ln69_29_fu_1115_p2;
reg   [15:0] add_ln69_29_reg_1793;
wire   [16:0] add_ln67_25_fu_1202_p2;
reg   [16:0] add_ln67_25_reg_1808;
wire    ap_CS_fsm_state17;
wire   [15:0] add_ln69_30_fu_1208_p2;
reg   [15:0] add_ln69_30_reg_1813;
wire   [16:0] add_ln67_29_fu_1217_p2;
reg   [16:0] add_ln67_29_reg_1818;
wire   [15:0] add_ln69_31_fu_1223_p2;
reg   [15:0] add_ln69_31_reg_1823;
wire    ap_CS_fsm_state18;
wire   [31:0] temp_fu_940_p2;
wire   [31:0] temp_1_fu_970_p2;
wire   [31:0] temp_2_fu_1048_p2;
wire   [31:0] temp_3_fu_1078_p2;
wire   [31:0] temp_4_fu_1156_p2;
wire   [31:0] temp_5_fu_1186_p2;
wire   [31:0] temp_6_fu_1258_p2;
wire   [31:0] temp_7_fu_1288_p2;
wire   [15:0] trunc_ln67_fu_680_p1;
wire   [15:0] trunc_ln67_1_fu_694_p1;
wire   [15:0] trunc_ln67_2_fu_708_p1;
wire   [15:0] trunc_ln67_3_fu_722_p1;
wire   [15:0] trunc_ln67_4_fu_736_p1;
wire   [15:0] trunc_ln67_5_fu_750_p1;
wire   [15:0] trunc_ln67_6_fu_764_p1;
wire   [15:0] trunc_ln67_7_fu_778_p1;
wire  signed [15:0] sext_ln67_8_fu_874_p0;
wire  signed [16:0] sext_ln69_8_fu_858_p1;
wire  signed [16:0] sext_ln67_8_fu_874_p1;
wire  signed [15:0] add_ln69_24_fu_884_p0;
wire  signed [15:0] sext_ln67_11_fu_889_p0;
wire  signed [16:0] sext_ln69_9_fu_861_p1;
wire  signed [16:0] sext_ln67_11_fu_889_p1;
wire  signed [15:0] add_ln69_25_fu_899_p0;
wire  signed [31:0] sext_ln67_fu_904_p1;
wire  signed [17:0] sext_ln67_9_fu_927_p1;
wire  signed [17:0] sext_ln69_fu_910_p1;
wire   [17:0] add_ln67_2_fu_930_p2;
wire  signed [31:0] sext_ln67_10_fu_936_p1;
wire   [31:0] add_ln67_fu_922_p2;
wire  signed [31:0] sext_ln67_1_fu_907_p1;
wire  signed [17:0] sext_ln67_12_fu_957_p1;
wire  signed [17:0] sext_ln69_1_fu_913_p1;
wire   [17:0] add_ln67_6_fu_960_p2;
wire  signed [31:0] sext_ln67_13_fu_966_p1;
wire   [31:0] add_ln67_4_fu_952_p2;
wire  signed [15:0] sext_ln67_14_fu_982_p0;
wire  signed [16:0] sext_ln69_10_fu_916_p1;
wire  signed [16:0] sext_ln67_14_fu_982_p1;
wire  signed [15:0] add_ln69_26_fu_992_p0;
wire  signed [15:0] sext_ln67_17_fu_997_p0;
wire  signed [16:0] sext_ln69_11_fu_919_p1;
wire  signed [16:0] sext_ln67_17_fu_997_p1;
wire  signed [15:0] add_ln69_27_fu_1007_p0;
wire  signed [31:0] sext_ln67_2_fu_1012_p1;
wire  signed [17:0] sext_ln67_15_fu_1035_p1;
wire  signed [17:0] sext_ln69_2_fu_1018_p1;
wire   [17:0] add_ln67_10_fu_1038_p2;
wire  signed [31:0] sext_ln67_16_fu_1044_p1;
wire   [31:0] add_ln67_8_fu_1030_p2;
wire  signed [31:0] sext_ln67_3_fu_1015_p1;
wire  signed [17:0] sext_ln67_18_fu_1065_p1;
wire  signed [17:0] sext_ln69_3_fu_1021_p1;
wire   [17:0] add_ln67_14_fu_1068_p2;
wire  signed [31:0] sext_ln67_19_fu_1074_p1;
wire   [31:0] add_ln67_12_fu_1060_p2;
wire  signed [15:0] sext_ln67_20_fu_1090_p0;
wire  signed [16:0] sext_ln69_12_fu_1024_p1;
wire  signed [16:0] sext_ln67_20_fu_1090_p1;
wire  signed [15:0] add_ln69_28_fu_1100_p0;
wire  signed [15:0] sext_ln67_23_fu_1105_p0;
wire  signed [16:0] sext_ln69_13_fu_1027_p1;
wire  signed [16:0] sext_ln67_23_fu_1105_p1;
wire  signed [15:0] add_ln69_29_fu_1115_p0;
wire  signed [31:0] sext_ln67_4_fu_1120_p1;
wire  signed [17:0] sext_ln67_21_fu_1143_p1;
wire  signed [17:0] sext_ln69_4_fu_1126_p1;
wire   [17:0] add_ln67_18_fu_1146_p2;
wire  signed [31:0] sext_ln67_22_fu_1152_p1;
wire   [31:0] add_ln67_16_fu_1138_p2;
wire  signed [31:0] sext_ln67_5_fu_1123_p1;
wire  signed [17:0] sext_ln67_24_fu_1173_p1;
wire  signed [17:0] sext_ln69_5_fu_1129_p1;
wire   [17:0] add_ln67_22_fu_1176_p2;
wire  signed [31:0] sext_ln67_25_fu_1182_p1;
wire   [31:0] add_ln67_20_fu_1168_p2;
wire  signed [15:0] sext_ln67_26_fu_1198_p0;
wire  signed [16:0] sext_ln69_14_fu_1132_p1;
wire  signed [16:0] sext_ln67_26_fu_1198_p1;
wire  signed [15:0] add_ln69_30_fu_1208_p0;
wire  signed [15:0] sext_ln67_29_fu_1213_p0;
wire  signed [16:0] sext_ln69_15_fu_1135_p1;
wire  signed [16:0] sext_ln67_29_fu_1213_p1;
wire  signed [15:0] add_ln69_31_fu_1223_p0;
wire  signed [31:0] sext_ln67_6_fu_1228_p1;
wire  signed [17:0] sext_ln67_27_fu_1245_p1;
wire  signed [17:0] sext_ln69_6_fu_1234_p1;
wire   [17:0] add_ln67_26_fu_1248_p2;
wire  signed [31:0] sext_ln67_28_fu_1254_p1;
wire   [31:0] add_ln67_24_fu_1240_p2;
wire  signed [31:0] sext_ln67_7_fu_1231_p1;
wire  signed [17:0] sext_ln67_30_fu_1275_p1;
wire  signed [17:0] sext_ln69_7_fu_1237_p1;
wire   [17:0] add_ln67_30_fu_1278_p2;
wire  signed [31:0] sext_ln67_31_fu_1284_p1;
wire   [31:0] add_ln67_28_fu_1270_p2;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 acc_0 = 32'd0;
#0 acc_1 = 32'd0;
#0 acc_2 = 32'd0;
#0 acc_3 = 32'd0;
#0 acc_4 = 32'd0;
#0 acc_5 = 32'd0;
#0 acc_6 = 32'd0;
#0 acc_7 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        acc_0 <= temp_fu_940_p2;
        acc_1 <= temp_1_fu_970_p2;
        add_ln67_13_reg_1758 <= add_ln67_13_fu_1001_p2;
        add_ln67_9_reg_1748 <= add_ln67_9_fu_986_p2;
        add_ln69_26_reg_1753 <= add_ln69_26_fu_992_p2;
        add_ln69_27_reg_1763 <= add_ln69_27_fu_1007_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        acc_2 <= temp_2_fu_1048_p2;
        acc_3 <= temp_3_fu_1078_p2;
        add_ln67_17_reg_1778 <= add_ln67_17_fu_1094_p2;
        add_ln67_21_reg_1788 <= add_ln67_21_fu_1109_p2;
        add_ln69_28_reg_1783 <= add_ln69_28_fu_1100_p2;
        add_ln69_29_reg_1793 <= add_ln69_29_fu_1115_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        acc_4 <= temp_4_fu_1156_p2;
        acc_5 <= temp_5_fu_1186_p2;
        add_ln67_25_reg_1808 <= add_ln67_25_fu_1202_p2;
        add_ln67_29_reg_1818 <= add_ln67_29_fu_1217_p2;
        add_ln69_30_reg_1813 <= add_ln69_30_fu_1208_p2;
        add_ln69_31_reg_1823 <= add_ln69_31_fu_1223_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        acc_6 <= temp_6_fu_1258_p2;
        acc_7 <= temp_7_fu_1288_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln67_1_reg_1718 <= add_ln67_1_fu_878_p2;
        add_ln67_5_reg_1728 <= add_ln67_5_fu_893_p2;
        add_ln69_22_reg_1708 <= add_ln69_22_fu_864_p2;
        add_ln69_23_reg_1713 <= add_ln69_23_fu_869_p2;
        add_ln69_24_reg_1723 <= add_ln69_24_fu_884_p2;
        add_ln69_25_reg_1733 <= add_ln69_25_fu_899_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln69_10_reg_1516 <= add_ln69_10_fu_798_p2;
        add_ln69_11_reg_1521 <= add_ln69_11_fu_803_p2;
        d_i_0_load_6_reg_1526 <= d_i_0_q0;
        d_i_1_load_6_reg_1532 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln69_12_reg_1548 <= add_ln69_12_fu_808_p2;
        add_ln69_13_reg_1553 <= add_ln69_13_fu_813_p2;
        d_i_0_load_7_reg_1558 <= d_i_0_q0;
        d_i_1_load_7_reg_1564 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln69_14_reg_1580 <= add_ln69_14_fu_818_p2;
        add_ln69_15_reg_1585 <= add_ln69_15_fu_823_p2;
        d_i_0_load_8_reg_1590 <= d_i_0_q0;
        d_i_1_load_8_reg_1596 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln69_16_reg_1612 <= add_ln69_16_fu_828_p2;
        add_ln69_17_reg_1617 <= add_ln69_17_fu_833_p2;
        d_i_0_load_9_reg_1622 <= d_i_0_q0;
        d_i_1_load_9_reg_1628 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln69_18_reg_1644 <= add_ln69_18_fu_838_p2;
        add_ln69_19_reg_1649 <= add_ln69_19_fu_843_p2;
        d_i_0_load_10_reg_1654 <= d_i_0_q0;
        d_i_1_load_10_reg_1660 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln69_1_reg_1343 <= add_ln69_1_fu_698_p2;
        add_ln69_reg_1335 <= add_ln69_fu_684_p2;
        d_i_0_load_1_reg_1348 <= d_i_0_q0;
        d_i_1_load_1_reg_1354 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln69_20_reg_1676 <= add_ln69_20_fu_848_p2;
        add_ln69_21_reg_1681 <= add_ln69_21_fu_853_p2;
        d_i_0_load_11_reg_1686 <= d_i_0_q0;
        d_i_1_load_11_reg_1692 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln69_2_reg_1373 <= add_ln69_2_fu_712_p2;
        add_ln69_3_reg_1381 <= add_ln69_3_fu_726_p2;
        d_i_0_load_2_reg_1386 <= d_i_0_q0;
        d_i_1_load_2_reg_1392 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln69_4_reg_1411 <= add_ln69_4_fu_740_p2;
        add_ln69_5_reg_1419 <= add_ln69_5_fu_754_p2;
        d_i_0_load_3_reg_1424 <= d_i_0_q0;
        d_i_1_load_3_reg_1430 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln69_6_reg_1449 <= add_ln69_6_fu_768_p2;
        add_ln69_7_reg_1457 <= add_ln69_7_fu_782_p2;
        d_i_0_load_4_reg_1462 <= d_i_0_q0;
        d_i_1_load_4_reg_1468 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln69_8_reg_1484 <= add_ln69_8_fu_788_p2;
        add_ln69_9_reg_1489 <= add_ln69_9_fu_793_p2;
        d_i_0_load_5_reg_1494 <= d_i_0_q0;
        d_i_1_load_5_reg_1500 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_load_reg_1310 <= d_i_0_q0;
        d_i_1_load_reg_1316 <= d_i_1_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        d_i_0_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_i_0_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_i_0_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_i_0_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_i_0_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_i_0_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_i_0_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_i_0_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_0_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_0_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_0_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_0_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_0_address0 = 64'd0;
    end else begin
        d_i_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_0_ce0 = 1'b1;
    end else begin
        d_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        d_i_1_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_i_1_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_i_1_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_i_1_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_i_1_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_i_1_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_i_1_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_i_1_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_i_1_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_1_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_1_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_1_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_1_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_1_address0 = 64'd0;
    end else begin
        d_i_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        d_i_1_ce0 = 1'b1;
    end else begin
        d_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        d_o_0_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        d_o_0_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        d_o_0_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_o_0_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_o_0_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_o_0_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_o_0_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_o_0_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_0_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_0_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_0_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_0_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_o_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_o_0_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_o_0_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_o_0_address0 = 64'd0;
    end else begin
        d_o_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        d_o_0_ce0 = 1'b1;
    end else begin
        d_o_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        d_o_0_d0 = add_ln69_30_reg_1813;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        d_o_0_d0 = add_ln69_28_reg_1783;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        d_o_0_d0 = add_ln69_26_reg_1753;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_o_0_d0 = add_ln69_24_reg_1723;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_o_0_d0 = add_ln69_22_fu_864_p2;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_o_0_d0 = add_ln69_20_fu_848_p2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_o_0_d0 = add_ln69_18_fu_838_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_o_0_d0 = add_ln69_16_fu_828_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_0_d0 = add_ln69_14_fu_818_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_0_d0 = add_ln69_12_fu_808_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_0_d0 = add_ln69_10_fu_798_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_0_d0 = add_ln69_8_fu_788_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_o_0_d0 = add_ln69_6_fu_768_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_o_0_d0 = add_ln69_4_fu_740_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_o_0_d0 = add_ln69_2_fu_712_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_o_0_d0 = add_ln69_fu_684_p2;
    end else begin
        d_o_0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        d_o_0_we0 = 1'b1;
    end else begin
        d_o_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        d_o_1_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        d_o_1_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        d_o_1_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_o_1_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_o_1_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_o_1_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_o_1_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_o_1_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_1_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_1_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_1_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_1_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_o_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_o_1_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_o_1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_o_1_address0 = 64'd0;
    end else begin
        d_o_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        d_o_1_ce0 = 1'b1;
    end else begin
        d_o_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        d_o_1_d0 = add_ln69_31_reg_1823;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        d_o_1_d0 = add_ln69_29_reg_1793;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        d_o_1_d0 = add_ln69_27_reg_1763;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        d_o_1_d0 = add_ln69_25_reg_1733;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_o_1_d0 = add_ln69_23_fu_869_p2;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        d_o_1_d0 = add_ln69_21_fu_853_p2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        d_o_1_d0 = add_ln69_19_fu_843_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_o_1_d0 = add_ln69_17_fu_833_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_o_1_d0 = add_ln69_15_fu_823_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_o_1_d0 = add_ln69_13_fu_813_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_o_1_d0 = add_ln69_11_fu_803_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_1_d0 = add_ln69_9_fu_793_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_o_1_d0 = add_ln69_7_fu_782_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_o_1_d0 = add_ln69_5_fu_754_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_o_1_d0 = add_ln69_3_fu_726_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_o_1_d0 = add_ln69_1_fu_698_p2;
    end else begin
        d_o_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        d_o_1_we0 = 1'b1;
    end else begin
        d_o_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_10_fu_1038_p2 = ($signed(sext_ln67_15_fu_1035_p1) + $signed(sext_ln69_2_fu_1018_p1));

assign add_ln67_12_fu_1060_p2 = ($signed(acc_3) + $signed(sext_ln67_3_fu_1015_p1));

assign add_ln67_13_fu_1001_p2 = ($signed(sext_ln69_11_fu_919_p1) + $signed(sext_ln67_17_fu_997_p1));

assign add_ln67_14_fu_1068_p2 = ($signed(sext_ln67_18_fu_1065_p1) + $signed(sext_ln69_3_fu_1021_p1));

assign add_ln67_16_fu_1138_p2 = ($signed(acc_4) + $signed(sext_ln67_4_fu_1120_p1));

assign add_ln67_17_fu_1094_p2 = ($signed(sext_ln69_12_fu_1024_p1) + $signed(sext_ln67_20_fu_1090_p1));

assign add_ln67_18_fu_1146_p2 = ($signed(sext_ln67_21_fu_1143_p1) + $signed(sext_ln69_4_fu_1126_p1));

assign add_ln67_1_fu_878_p2 = ($signed(sext_ln69_8_fu_858_p1) + $signed(sext_ln67_8_fu_874_p1));

assign add_ln67_20_fu_1168_p2 = ($signed(acc_5) + $signed(sext_ln67_5_fu_1123_p1));

assign add_ln67_21_fu_1109_p2 = ($signed(sext_ln69_13_fu_1027_p1) + $signed(sext_ln67_23_fu_1105_p1));

assign add_ln67_22_fu_1176_p2 = ($signed(sext_ln67_24_fu_1173_p1) + $signed(sext_ln69_5_fu_1129_p1));

assign add_ln67_24_fu_1240_p2 = ($signed(acc_6) + $signed(sext_ln67_6_fu_1228_p1));

assign add_ln67_25_fu_1202_p2 = ($signed(sext_ln69_14_fu_1132_p1) + $signed(sext_ln67_26_fu_1198_p1));

assign add_ln67_26_fu_1248_p2 = ($signed(sext_ln67_27_fu_1245_p1) + $signed(sext_ln69_6_fu_1234_p1));

assign add_ln67_28_fu_1270_p2 = ($signed(acc_7) + $signed(sext_ln67_7_fu_1231_p1));

assign add_ln67_29_fu_1217_p2 = ($signed(sext_ln69_15_fu_1135_p1) + $signed(sext_ln67_29_fu_1213_p1));

assign add_ln67_2_fu_930_p2 = ($signed(sext_ln67_9_fu_927_p1) + $signed(sext_ln69_fu_910_p1));

assign add_ln67_30_fu_1278_p2 = ($signed(sext_ln67_30_fu_1275_p1) + $signed(sext_ln69_7_fu_1237_p1));

assign add_ln67_4_fu_952_p2 = ($signed(acc_1) + $signed(sext_ln67_1_fu_907_p1));

assign add_ln67_5_fu_893_p2 = ($signed(sext_ln69_9_fu_861_p1) + $signed(sext_ln67_11_fu_889_p1));

assign add_ln67_6_fu_960_p2 = ($signed(sext_ln67_12_fu_957_p1) + $signed(sext_ln69_1_fu_913_p1));

assign add_ln67_8_fu_1030_p2 = ($signed(acc_2) + $signed(sext_ln67_2_fu_1012_p1));

assign add_ln67_9_fu_986_p2 = ($signed(sext_ln69_10_fu_916_p1) + $signed(sext_ln67_14_fu_982_p1));

assign add_ln67_fu_922_p2 = ($signed(acc_0) + $signed(sext_ln67_fu_904_p1));

assign add_ln69_10_fu_798_p2 = ($signed(d_i_0_load_5_reg_1494) + $signed(add_ln69_2_reg_1373));

assign add_ln69_11_fu_803_p2 = ($signed(d_i_1_load_5_reg_1500) + $signed(add_ln69_3_reg_1381));

assign add_ln69_12_fu_808_p2 = ($signed(d_i_0_load_6_reg_1526) + $signed(add_ln69_4_reg_1411));

assign add_ln69_13_fu_813_p2 = ($signed(d_i_1_load_6_reg_1532) + $signed(add_ln69_5_reg_1419));

assign add_ln69_14_fu_818_p2 = ($signed(d_i_0_load_7_reg_1558) + $signed(add_ln69_6_reg_1449));

assign add_ln69_15_fu_823_p2 = ($signed(d_i_1_load_7_reg_1564) + $signed(add_ln69_7_reg_1457));

assign add_ln69_16_fu_828_p2 = ($signed(d_i_0_load_8_reg_1590) + $signed(add_ln69_8_reg_1484));

assign add_ln69_17_fu_833_p2 = ($signed(d_i_1_load_8_reg_1596) + $signed(add_ln69_9_reg_1489));

assign add_ln69_18_fu_838_p2 = ($signed(d_i_0_load_9_reg_1622) + $signed(add_ln69_10_reg_1516));

assign add_ln69_19_fu_843_p2 = ($signed(d_i_1_load_9_reg_1628) + $signed(add_ln69_11_reg_1521));

assign add_ln69_1_fu_698_p2 = ($signed(d_i_1_load_reg_1316) + $signed(trunc_ln67_1_fu_694_p1));

assign add_ln69_20_fu_848_p2 = ($signed(d_i_0_load_10_reg_1654) + $signed(add_ln69_12_reg_1548));

assign add_ln69_21_fu_853_p2 = ($signed(d_i_1_load_10_reg_1660) + $signed(add_ln69_13_reg_1553));

assign add_ln69_22_fu_864_p2 = ($signed(d_i_0_load_11_reg_1686) + $signed(add_ln69_14_reg_1580));

assign add_ln69_23_fu_869_p2 = ($signed(d_i_1_load_11_reg_1692) + $signed(add_ln69_15_reg_1585));

assign add_ln69_24_fu_884_p0 = d_i_0_q0;

assign add_ln69_24_fu_884_p2 = ($signed(add_ln69_24_fu_884_p0) + $signed(add_ln69_16_reg_1612));

assign add_ln69_25_fu_899_p0 = d_i_1_q0;

assign add_ln69_25_fu_899_p2 = ($signed(add_ln69_25_fu_899_p0) + $signed(add_ln69_17_reg_1617));

assign add_ln69_26_fu_992_p0 = d_i_0_q0;

assign add_ln69_26_fu_992_p2 = ($signed(add_ln69_26_fu_992_p0) + $signed(add_ln69_18_reg_1644));

assign add_ln69_27_fu_1007_p0 = d_i_1_q0;

assign add_ln69_27_fu_1007_p2 = ($signed(add_ln69_27_fu_1007_p0) + $signed(add_ln69_19_reg_1649));

assign add_ln69_28_fu_1100_p0 = d_i_0_q0;

assign add_ln69_28_fu_1100_p2 = ($signed(add_ln69_28_fu_1100_p0) + $signed(add_ln69_20_reg_1676));

assign add_ln69_29_fu_1115_p0 = d_i_1_q0;

assign add_ln69_29_fu_1115_p2 = ($signed(add_ln69_29_fu_1115_p0) + $signed(add_ln69_21_reg_1681));

assign add_ln69_2_fu_712_p2 = ($signed(d_i_0_load_1_reg_1348) + $signed(trunc_ln67_2_fu_708_p1));

assign add_ln69_30_fu_1208_p0 = d_i_0_q0;

assign add_ln69_30_fu_1208_p2 = ($signed(add_ln69_30_fu_1208_p0) + $signed(add_ln69_22_reg_1708));

assign add_ln69_31_fu_1223_p0 = d_i_1_q0;

assign add_ln69_31_fu_1223_p2 = ($signed(add_ln69_31_fu_1223_p0) + $signed(add_ln69_23_reg_1713));

assign add_ln69_3_fu_726_p2 = ($signed(d_i_1_load_1_reg_1354) + $signed(trunc_ln67_3_fu_722_p1));

assign add_ln69_4_fu_740_p2 = ($signed(d_i_0_load_2_reg_1386) + $signed(trunc_ln67_4_fu_736_p1));

assign add_ln69_5_fu_754_p2 = ($signed(d_i_1_load_2_reg_1392) + $signed(trunc_ln67_5_fu_750_p1));

assign add_ln69_6_fu_768_p2 = ($signed(d_i_0_load_3_reg_1424) + $signed(trunc_ln67_6_fu_764_p1));

assign add_ln69_7_fu_782_p2 = ($signed(d_i_1_load_3_reg_1430) + $signed(trunc_ln67_7_fu_778_p1));

assign add_ln69_8_fu_788_p2 = ($signed(d_i_0_load_4_reg_1462) + $signed(add_ln69_reg_1335));

assign add_ln69_9_fu_793_p2 = ($signed(d_i_1_load_4_reg_1468) + $signed(add_ln69_1_reg_1343));

assign add_ln69_fu_684_p2 = ($signed(d_i_0_load_reg_1310) + $signed(trunc_ln67_fu_680_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign sext_ln67_10_fu_936_p1 = $signed(add_ln67_2_fu_930_p2);

assign sext_ln67_11_fu_889_p0 = d_i_1_q0;

assign sext_ln67_11_fu_889_p1 = sext_ln67_11_fu_889_p0;

assign sext_ln67_12_fu_957_p1 = $signed(add_ln67_5_reg_1728);

assign sext_ln67_13_fu_966_p1 = $signed(add_ln67_6_fu_960_p2);

assign sext_ln67_14_fu_982_p0 = d_i_0_q0;

assign sext_ln67_14_fu_982_p1 = sext_ln67_14_fu_982_p0;

assign sext_ln67_15_fu_1035_p1 = $signed(add_ln67_9_reg_1748);

assign sext_ln67_16_fu_1044_p1 = $signed(add_ln67_10_fu_1038_p2);

assign sext_ln67_17_fu_997_p0 = d_i_1_q0;

assign sext_ln67_17_fu_997_p1 = sext_ln67_17_fu_997_p0;

assign sext_ln67_18_fu_1065_p1 = $signed(add_ln67_13_reg_1758);

assign sext_ln67_19_fu_1074_p1 = $signed(add_ln67_14_fu_1068_p2);

assign sext_ln67_1_fu_907_p1 = d_i_1_load_reg_1316;

assign sext_ln67_20_fu_1090_p0 = d_i_0_q0;

assign sext_ln67_20_fu_1090_p1 = sext_ln67_20_fu_1090_p0;

assign sext_ln67_21_fu_1143_p1 = $signed(add_ln67_17_reg_1778);

assign sext_ln67_22_fu_1152_p1 = $signed(add_ln67_18_fu_1146_p2);

assign sext_ln67_23_fu_1105_p0 = d_i_1_q0;

assign sext_ln67_23_fu_1105_p1 = sext_ln67_23_fu_1105_p0;

assign sext_ln67_24_fu_1173_p1 = $signed(add_ln67_21_reg_1788);

assign sext_ln67_25_fu_1182_p1 = $signed(add_ln67_22_fu_1176_p2);

assign sext_ln67_26_fu_1198_p0 = d_i_0_q0;

assign sext_ln67_26_fu_1198_p1 = sext_ln67_26_fu_1198_p0;

assign sext_ln67_27_fu_1245_p1 = $signed(add_ln67_25_reg_1808);

assign sext_ln67_28_fu_1254_p1 = $signed(add_ln67_26_fu_1248_p2);

assign sext_ln67_29_fu_1213_p0 = d_i_1_q0;

assign sext_ln67_29_fu_1213_p1 = sext_ln67_29_fu_1213_p0;

assign sext_ln67_2_fu_1012_p1 = d_i_0_load_1_reg_1348;

assign sext_ln67_30_fu_1275_p1 = $signed(add_ln67_29_reg_1818);

assign sext_ln67_31_fu_1284_p1 = $signed(add_ln67_30_fu_1278_p2);

assign sext_ln67_3_fu_1015_p1 = d_i_1_load_1_reg_1354;

assign sext_ln67_4_fu_1120_p1 = d_i_0_load_2_reg_1386;

assign sext_ln67_5_fu_1123_p1 = d_i_1_load_2_reg_1392;

assign sext_ln67_6_fu_1228_p1 = d_i_0_load_3_reg_1424;

assign sext_ln67_7_fu_1231_p1 = d_i_1_load_3_reg_1430;

assign sext_ln67_8_fu_874_p0 = d_i_0_q0;

assign sext_ln67_8_fu_874_p1 = sext_ln67_8_fu_874_p0;

assign sext_ln67_9_fu_927_p1 = $signed(add_ln67_1_reg_1718);

assign sext_ln67_fu_904_p1 = d_i_0_load_reg_1310;

assign sext_ln69_10_fu_916_p1 = d_i_0_load_9_reg_1622;

assign sext_ln69_11_fu_919_p1 = d_i_1_load_9_reg_1628;

assign sext_ln69_12_fu_1024_p1 = d_i_0_load_10_reg_1654;

assign sext_ln69_13_fu_1027_p1 = d_i_1_load_10_reg_1660;

assign sext_ln69_14_fu_1132_p1 = d_i_0_load_11_reg_1686;

assign sext_ln69_15_fu_1135_p1 = d_i_1_load_11_reg_1692;

assign sext_ln69_1_fu_913_p1 = d_i_1_load_4_reg_1468;

assign sext_ln69_2_fu_1018_p1 = d_i_0_load_5_reg_1494;

assign sext_ln69_3_fu_1021_p1 = d_i_1_load_5_reg_1500;

assign sext_ln69_4_fu_1126_p1 = d_i_0_load_6_reg_1526;

assign sext_ln69_5_fu_1129_p1 = d_i_1_load_6_reg_1532;

assign sext_ln69_6_fu_1234_p1 = d_i_0_load_7_reg_1558;

assign sext_ln69_7_fu_1237_p1 = d_i_1_load_7_reg_1564;

assign sext_ln69_8_fu_858_p1 = d_i_0_load_8_reg_1590;

assign sext_ln69_9_fu_861_p1 = d_i_1_load_8_reg_1596;

assign sext_ln69_fu_910_p1 = d_i_0_load_4_reg_1462;

assign temp_1_fu_970_p2 = ($signed(sext_ln67_13_fu_966_p1) + $signed(add_ln67_4_fu_952_p2));

assign temp_2_fu_1048_p2 = ($signed(sext_ln67_16_fu_1044_p1) + $signed(add_ln67_8_fu_1030_p2));

assign temp_3_fu_1078_p2 = ($signed(sext_ln67_19_fu_1074_p1) + $signed(add_ln67_12_fu_1060_p2));

assign temp_4_fu_1156_p2 = ($signed(sext_ln67_22_fu_1152_p1) + $signed(add_ln67_16_fu_1138_p2));

assign temp_5_fu_1186_p2 = ($signed(sext_ln67_25_fu_1182_p1) + $signed(add_ln67_20_fu_1168_p2));

assign temp_6_fu_1258_p2 = ($signed(sext_ln67_28_fu_1254_p1) + $signed(add_ln67_24_fu_1240_p2));

assign temp_7_fu_1288_p2 = ($signed(sext_ln67_31_fu_1284_p1) + $signed(add_ln67_28_fu_1270_p2));

assign temp_fu_940_p2 = ($signed(sext_ln67_10_fu_936_p1) + $signed(add_ln67_fu_922_p2));

assign trunc_ln67_1_fu_694_p1 = acc_1[15:0];

assign trunc_ln67_2_fu_708_p1 = acc_2[15:0];

assign trunc_ln67_3_fu_722_p1 = acc_3[15:0];

assign trunc_ln67_4_fu_736_p1 = acc_4[15:0];

assign trunc_ln67_5_fu_750_p1 = acc_5[15:0];

assign trunc_ln67_6_fu_764_p1 = acc_6[15:0];

assign trunc_ln67_7_fu_778_p1 = acc_7[15:0];

assign trunc_ln67_fu_680_p1 = acc_0[15:0];

endmodule //array_io
